#pragma once

#define CLIENT_CERT_TAG 1
#define CLIENT_KEY_TAG 2

#define CLIENT_CERT 1
#define TLS_PEER_HOSTNAME "zephyr-client"

/**
 * The inc files are generated by Zephyr in .pio/<board name>/zephyr/include/generated and are referenced
 * in the platformio.ini file.
 */
static const unsigned char client_certificate[] = {
#include "client_cert.der.inc"
};

static const unsigned char client_key[] = {
#include "client_key.der.inc"
};
static const unsigned char root_certificate[] = {
#include "lab5e_ca.der.inc"
};
