#pragma once

#define ROOT_CERT_TAG 1
#define CLIENT_CERT_TAG 2

#define CLIENT_CERT 1
#define TLS_PEER_HOSTNAME "stm32"

/**
 * The inc files are generated by Zephyr in .pio/<board name>/zephyr/include/generated and are referenced
 * in the platformio.ini file.
 */
static const unsigned char client_certificate[] = {
#include "client.crt.inc"
    0,
};

static const unsigned char client_key[] = {
#include "client.key.inc"
    0,
};
static const unsigned char root_certificate[] = {
#include "root-chain.crt.inc"
    0,
};
